# Generated by Django 4.2.2 on 2023-06-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_ordermodel_email_ordermodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('FF', 'Fulfilled'), ('DF', 'Deferred'), ('DN', 'DENIED')], default='FF', max_length=2),
        ),
    ]
