# Generated by Django 4.2.2 on 2023-07-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_ordermodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='price',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('Fulfilled', 'Fulfilled'), ('Deferred', 'Deferred'), ('Denied', 'Denied')], default='Deferred', max_length=10),
        ),
    ]
