# Generated by Django 4.2.3 on 2023-07-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_menuitem_price_remove_ordermodel_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('snack', models.CharField(blank=True, max_length=100)),
                ('argument', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Fulfilled', 'Fulfilled'), ('Deferred', 'Deferred'), ('Denied', 'Denied'), ('Pending', 'Pending')], default='Deferred', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('Fulfilled', 'Fulfilled'), ('Deferred', 'Deferred'), ('Denied', 'Denied'), ('Pending', 'Pending')], default='Deferred', max_length=10),
        ),
    ]
