# Generated by Django 4.2.3 on 2023-07-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_newrequestmodel_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrequestmodel',
            name='status',
            field=models.CharField(choices=[('Fulfilled', 'Fulfilled'), ('Deferred', 'Deferred'), ('Denied', 'Denied'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('Fulfilled', 'Fulfilled'), ('Deferred', 'Deferred'), ('Denied', 'Denied'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
